// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoRazorFinal.Models
{
    public partial class Cliente
    {
        public Cliente()
        {
            Puntuacion = new HashSet<Puntuacion>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public DateTime? FechaRegistro { get; set; }

        public virtual ICollection<Puntuacion> Puntuacion { get; set; }
    }
}