// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoRazorFinal.Models
{
    public partial class Disco
    {
        public Disco()
        {
            DiscoTipo = new HashSet<DiscoTipo>();
            Puntuacion = new HashSet<Puntuacion>();
        }

        public int IdDisco { get; set; }
        public string Titulo { get; set; }
        public double? Agno { get; set; }
        public int IdInterprete { get; set; }

        public virtual Interprete IdInterpreteNavigation { get; set; }
        public virtual ICollection<DiscoTipo> DiscoTipo { get; set; }
        public virtual ICollection<Puntuacion> Puntuacion { get; set; }
    }
}