// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProyectoRazorFinal.Models
{
    public partial class Interprete
    {
        public Interprete()
        {
            Disco = new HashSet<Disco>();
        }

        public string Interprete1 { get; set; }
        public int IdInterprete { get; set; }

        public virtual ICollection<Disco> Disco { get; set; }
    }
}